name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Install necessary packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libgmp-dev libboost-dev libboost-filesystem-dev libboost-system-dev libreadline-dev gcc g++ make

      - name: Configure build
        run: ./configure

      - name: Compile and run tests
        run: |
          make -j8 check examples server
          pushd src/CoCoA-5
          make -j8 check wordlist
          popd
